- name: Check number
  hosts: local
  connection: local
  vars: 
    number: 21
  tasks:
  - name: my number is greater than 15
    ansible.builtin.debug:
      msg: "= Number {{ number }} is greater than 15"
    when: number > 15