- name: Check number
  hosts: local
  connection: local
  vars: 
    number: 11
  tasks:
  - name: Print the greater number
    ansible.builtin.debug:
      msg: "check my number {{ number }} is greater than 15"
    when: number > 15