- name: Install Packages
  hosts: web
  become: yes
  tasks: 
  - name: Install Packages
    ansible.builtin.package:
      name: "{{ item.name }}"
      state: installed  
    loop:
      - nginx
      - mysql
      - gcc
      - git
      - zip