plugin: amazon.aws.aws_ec2
regions:
  - us-east-1
hostnames:
  - private-ip-address






# plugin: amazon.aws.aws_ec2
# regions:
#   - us-east-1
# hostnames:
#   # You can also specify a list in order of precedence for hostname variables.
#   - private-ip-address
