

- name: Nginx Check
  hosts: web
  become: yes

- name: Gather package facts
  ansible.builtin.package_facts:

- name: Print nginx status
  debug:
    msg: "NGINX is installed"
  when: "'nginx' in ansible_facts.packages"

- name: Install nginx if not installed
  ansible.builtin.package:
    name: nginx
    state: present
  when: "'nginx' not in ansible_facts.packages"
