


- name: Check if nginx is already installed
  ansible.builtin.shell: dpkg -l | grep -w nginx
  register: nginx_check
  ignore_errors: true

- name: Install nginx if not installed
  ansible.builtin.apt:
    name: nginx
    state: present
    update_cache: yes
  when: nginx_check.rc != 0
