  - name: Install and run Nginx
    hosts: web
    become: yes
    tasks:

    - name: Gather package facts
      ansible.builtin.package_facts:

    - name: Display if nginx is installed
      debug:
        msg: "NGINX is already installed"
      when: "'nginx' in ansible_facts.packages"

    - name: Install nginx if not installed
      ansible.builtin.package:
        name: nginx
        state: present
      when: "'nginx' not in ansible_facts.packages"
